### ISSUE TITLE
Cassandra output is not compatible with databases requiring CA-based TLS

### ISSUE THREAD

**Issue by codingconcepts** [Jeffail/benthos#549]
Without the use of `cluster.SslOpts`, the following code won't work:

``` go
cluster := gocql.NewCluster("cassandra.REGION.amazonaws.com:9142")
cluster.Authenticator = gocql.PasswordAuthenticator{
	Username: "USERNAME",
	Password: "PASSWORD",
}
			
cluster.SslOpts = &gocql.SslOptions{
	CaPath: "/PATH/TO/AmazonRootCA1.pem",
}

cluster.Consistency = gocql.LocalQuorum
cluster.DisableInitialHostLookup = true

session, err := cluster.CreateSession()
```

I've tested with AWS Keyspaces but I'm fairly sure this would be the same for other providers/databases too.

I suggest the addition of the following fields to the `CassandraConfig` struct:

``` yaml
ca_cert_path: /PATH/TO/AmazonRootCA1.pem
disable_initial_host_lookup: true
```

**Comment by Jeffail** [comment]
Hey @codingconcepts, should be quick to add but I'm going to expose these as a standard tls config so it matches other components (https://www.benthos.dev/docs/components/inputs/amqp_1#tls)

**Comment by codingconcepts** [comment]
Hey @Jeffail, perfect, that sounds great 👍

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/880cf117097b7c639ae08e58b2068e59a12761ee, it'll be included in the next release.

**Comment by codingconcepts** [comment]
Hey @Jeffail,

I think there'll be an issue setting `SslOpts` here: https://github.com/Jeffail/benthos/blob/master/lib/output/cassandra.go#L201 as from what I can see with `gocql`, the `SslOpts` won't be set as part of the call to `NewCluster`.

**Comment by Jeffail** [comment]
@codingconcepts woops! Well spotted, I think this is fixed with https://github.com/Jeffail/benthos/commit/49ea599f961d2ef34e16a2f3ae0f2c363eb37d1a, I can run it with ssl config params without crashing but I don't have a set up to test that the ssl params work.

**Comment by codingconcepts** [comment]
Hey @Jeffail,

Almost there! I just gave it a whirl locally and it's still missing one important bit (and another helpful bit):

**Important bit**:
The `CaPath` field needs to be set:

``` go
if c.tlsConf != nil {
	conn.SslOpts = &gocql.SslOptions{
		Config: c.tlsConf,
		CaPath: c.conf.TLS.RootCAsFile,
	}
}
```

**Helpful bit**:
This will make the client connect to Cassandra a lot quicker and makes sense to be a config field imo:

``` go
conn.DisableInitialHostLookup = true
```

Thanks for your work on this, Ash,

Rob

**Comment by Jeffail** [comment]
Another try 😅 https://github.com/Jeffail/benthos/commit/bbddd9d16d759babbd43ca7879db839623def7f3, I've added disabling the host lookup as a field, would it make sense to make it true by default here? I'm not particularly clear on the impact it has.

**Comment by codingconcepts** [comment]
Fantastic, that's working beautifully, @Jeffail. Thank you.

I think leave it at false by default. As it's something you have to opt out of in the gocql code, I think it should also be something you have to opt out of in Benthos (personally).

Would you mind adding this to an rc2 Docker image?


Thanks again,

Rob

**Comment by Jeffail** [comment]
@codingconcepts, I've pushed an image `jeffail/benthos:3.33.0-rc1-8-g841c7416` from the current master
